### PR TITLE
Tell me im doing this to the right fork

### PR DESCRIPTION
**Pull request by moonheart08**
[Changelogs]: # (Please make a changelog if you're adding, removing or changing content that'll affect players. This includes, but is not limited to, new features, sprites, sounds; balance changes; map edits and important fixes)
[]: # (See here for how to easily make a changelog: https://github.com/tgstation/tgstation/wiki/Changelogs. An example changelog has been provided below. Please edit or remove)

:cl: optional name here
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
wip: added a few works in progress
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
experiment: added an experimental thingy
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 

Intended for OBA-code not TG!

### CODE REVIEW

**Comment by Gwolfski** [comment]
this is the correct fork, yes

**Comment by Gwolfski** [comment]
I'll fix the conflicts this evening if you want

**Comment by moonheart08** [comment]
@Gwolfski Please do so. I have no idea how haha. (Just discard the basemap.dm changes, and add the Centcomm.dmm changes. Obviously discard the config change unless a new setting was added)

**Comment by Gwolfski** [comment]
around the 20th ill get my pc delivered, will be able to merger and test then.

**Comment by moonheart08** [comment]
@Gwolfski Surely its here by now, a entire month later. *remind*

**Comment by Gwolfski** [comment]
right. lemme fix this

**Comment by moonheart08** [comment]
@Gwolfski Dear god what did you break over there. Ets try again.

**Comment by moonheart08** [comment]
orrr, let me follow some advice...

**Pull request closed without merging**
